package.json, src/base-components/dialog-base.js, src/components/loader.js, src/icons/circle-loader.js, src/icons/index.js, src/index.js, stories/dialog.stories.js, stories/loader.stories.js, tailwind.config.js, yarn.lock
https://user-images.githubusercontent.com/50936670/122482118-f1e40600-cf9d-11eb-9467-9dab04746c01.mov
=> [G2M] Loader

.github/ISSUE_TEMPLATE/design-update---components.md, .github/ISSUE_TEMPLATE/design-update---design-tokens.md
added two new issue templates - one for component design updates and one for design token updates
=> Update issue templates - new design update templates

package.json, src/base-components/dropdown-base/index.js, src/components/dropdown-select-steps.js, src/components/dropdown-select.js, stories/dropdown.stories.js
- Added dropdown root container styling
- Added onSelect return value and index
- Changed package version to 0.1.0-alpha.6
=> [G2M] Dropdown styling & onSelect {value, index}

src/components/modal/content.js, src/components/modal/footer.js, src/components/modal/header.js, src/components/modal/index.js, stories/modal.stories.js
- Refactor modal structure for better usage
=> [G2M] modal - refactor structure

package.json, src/base-components/toast-base.js, src/components/pagination/index.js, src/components/tooltip.js, src/index.js, stories/tooltip.stories.js, tailwind.config.js
fix #52 
- Add Tooltip component using toast base component
=> [G2M] - Tooltip Component

package.json, src/base-components/input-base.js, src/components/dropdown-auto-complete.js, src/components/dropdown-select.js, src/components/text-field.js, src/components/toast.js, stories/dropdown.stories.js
- Added on click delete prop for input/textfield component
=> [G2M] add Input base on delete prop

package.json, src/components/toast.js, stories/toast.stories.js
- Added timeout feature for Toast component
- Added fade-in & fade-out animation
=> [G2M] Toast - timeout feature for connection hub

src/components/dropdown-select.js, stories/dropdown.stories.js
allows custom styling (for example, no capitalization or custom colour) to the selected item of a `DropdownSelect`
=> [G2M] dropdown - allow contentTitle class

.github/workflows/chromatic.yml
**Changes:**
- add chromatic job to create Chromatic Storybook link in PR github page. (see below)
=> [G2M] devops - add  storybook-pr-comment to chromatic jobs

src/base-components/dropdown-base/index.js
[ref](https://eqworks.slack.com/archives/GSNL88FQW/p1641996779019000)
before:
after:
closes EQWorks/widget-studio#62
=> [G2M] DropdownBase - fix disabled placeholder color

src/index.js, src/utils/custom-scroll.js, stories/custom-scroll.stories.js
- Created customScrollbar util
Should we add hover styling?? so it looks darker or wider although this only work on -webkit browsers such as CHROME
=> [G2M] Custom Scrollbar styling for containers

src/base-components/accordion-base/panel-base.js, src/components/dropdown-select.js
rectifying some console warnings found while working on EQWorks/widget-studio#65. Both are my mistakes :skull:
=> [G2M] Misc/reduce console warnings

src/components/dropdown-auto-center/index.js, src/components/pagination.js
- FIXED rowsPerPage data access 
- FIXED proptype error
=> [G2M] pagination - onSelect data access fix for LUMEN-TABLE

package.json, src/base-components/input-base.js, src/components/pagination.js, src/components/text-field.js, tailwind.config.js
=> [G2M] textfield - fix focus, onSubmit & suffix problems

package.json, src/base-components/checkbox-base/index.js
**Changes:**
- style checkbox with class `form-checkbox`
**Reference:**
- https://eqworks.slack.com/archives/GV827LS0M/p1645034774326669
=> [G2M] checkbox - style with classes instead of input element selectors

.github/ISSUE_TEMPLATE/design-update---components.md
- behaviour section is now 'types'
- removed styling variations section
- new anatomy section
=> Update issue templates - revise design guide format

package.json, src/components/checkbox.js
**[Storybook Deployed](https://60d0cd6c298707003972699d-suicodqhbr.chromatic.com/?path=/story/checkbox--normal)**
**Changes:**
fix - use default checked value if no indeterminate or default values given
=> [G2M] checkbox

package.json, src/base-components/checkbox-base/index.js, src/base-components/dialog-base.js, src/base-components/range-slider-base/index.js, src/components/checkbox.js, src/components/range-slider-label/index.js, src/components/switch-rect/index.js, src/components/text-field.js, src/index.js, stories/slider.stories.js
- Fixed Dialog - onClick event propagation & overlay styling
- Added Checkbox - check state watch useEffect for update & showlabel option
- Added RangeSlider - custom tooltip & label feature
These fixes are for lumen-table updates. Let me know if it will affect any of your projects
=> [G2M] Dialog / Checkbox / Range-Slider - small fixes and new features

src/components/area.js, stories/textfield.stories.js
- Fixed textfield.area maxLength issue
It is default NaN (unlimited) without count and if there is a limit there will be a count
=> [G2M] textfield - fix textarea length limit

src/components/progress-indicator.js, src/index.js, stories/progress-indicator.stories.js
**Changes:**
- add `ProgressIndicator` component
**Screenshots:**
=> [G2M] Progress/indicator

package.json, src/components/dropdown-auto-center/index.js, src/components/pagination.js, stories/dropdown.stories.js, stories/pagination.stories.js
- please see storybook example for new usage in getting data and displaying them workflow
=> [G2M] pagination - change item array to item length

colors.js, package.json, src/base-components/button-base.js, src/components/label.js, src/index.js, stories/chip.stories.js, stories/label.stories.js, tailwind.config.js
fix #110 
- Added label component
- Added neutral-800 color
=> [G2M] - Add Label chip component

src/base-components/input-base.js, src/components/date-picker.js, stories/date-picker.stories.js
it is a feature for the current widget studio calendar/date-picker which needs to be replaced
=> [G2M] date-picker - add minDate & maxDate option

package.json, src/base-components/input-base.js
this fix is for the close icon issue in https://github.com/EQWorks/widget-studio/pull/127
=> [G2M] input-base - change onClick to onMouseDown for onBlur event

package.json, src/components/dropdown-select.js, stories/dropdown.stories.js
- Added prevent deselect feature for dropdown
https://user-images.githubusercontent.com/46459367/178582676-3d2661d7-3788-43eb-bd06-9f6ad3e19401.mov
=> [G2M] Dropdown deselection

package.json, src/components/dropdown-select.js, stories/dropdown.stories.js
need this fix for https://github.com/EQWorks/widget-studio/pull/141 changes
=> [G2M] dropdown-select - fix multiselect limit

package.json, src/base-components/textarea-base.js, src/components/area.js
need this for https://github.com/EQWorks/widget-studio/pull/149
=> [G2M] Textarea - change classes & onFocus, onBlur prop access

package.json, src/base-components/textarea-base.js, src/components/area.js, src/components/text-field.js
for https://github.com/EQWorks/widget-studio/pull/166
- Fixed Textfield value undefined when maxLength is used
- Fixed Textfield.Area initial value
=> [G2M] Textfield value fix

package.json, src/components/button.js
Fixes #144 
- Event bubbling will no longer occur by default in nested React components
=> [G2M] Button - add stopPropagation as default value for button component

package.json, src/components/loader.js, stories/loader.stories.js
- Refactor custom class usage for Loader component
=> [G2M] Refactor loader component custom class usage

package.json, src/components/side-navbar/index.js, src/components/side-navbar/side-bar-footer.js, src/components/side-navbar/side-bar-header.js, src/components/side-navbar/side-bar-item.js, src/components/side-navbar/side-bar-menu.js, src/index.js, src/styles/tailwind.css, stories/side-navbar.stories.js, tailwind.config.js
- Added side-navbar component
- Added side-navbar header, menu, item & footer component
- Added new spacing in tailwindConfig 25px & 250px
- Added new font family in tailwindConfig font-rc ( radio canada )
PD: This is only the default simple version to update it for COX dashboard changes. Dropdown & Nested features will be added in future iteration.
**FIGMA:** https://www.figma.com/file/Tzb6u7o8fKixoFS9yXkdj7/Lumen-Components?node-id=368%3A38956
=> [G2M] side-navbar - create side-navbar component

package.json, src/components/area.js, src/components/button-group.js, src/components/button.js, src/components/card.js, src/components/checkbox.js, src/components/chip.js, src/components/dropdown-auto-center/index.js, src/components/dropdown-auto-complete.js, src/components/dropdown-select-steps.js, src/components/dropdown-select.js, src/components/label.js, src/components/layout/index.js, src/components/layout/sider.js, src/components/loader.js, src/components/message.js, src/components/modal/index.js, src/components/pagination.js, src/components/switch-rect/index.js, src/components/switch-round/index.js, src/components/switch-square/index.js, src/components/text-field.js, src/components/toast.js, src/components/tooltip.js
- Added classname to all componenets for easier selection and debug in the user side
=> [G2M] Add classname 

package.json, src/components/skeleton/barline.js, src/components/skeleton/index.js, src/components/skeleton/line.js, src/components/skeleton/pyramid.js, stories/skeleton.stories.js
Added views for Pyramid, Line and Barline graphs.
=> [G2M] Skeleton Views

package.json, src/components/radio-group.js, src/components/radio.js, src/index.js, stories/radio.stories.js
resolves #160 
- Added Radio + RadioGroup component
=> [G2M] Radio button

package.json, src/modules/login.js
resolves #163 
- Added props to sider image so user can modify style
- Updated frontend design to reflect changes found on [figma](https://www.figma.com/file/RB5JLQk54JgzUK6a50ej7S/COX-Dashboard?node-id=4814%3A142402&t=WYz6K7U4JfMJhPw9-0)
=> [G2M] login module design updated

package.json, src/components/skeleton/bar.js, src/components/skeleton/index.js, src/components/skeleton/stat.js, src/components/skeleton/text.js, stories/skeleton.stories.js
resovles #169 
- Added support for text widget
- Changed border-radius to rounded corners for skeletons using rect
=> [G2M] Added Text Widget Skeleton

package.json, src/components/area.js
https://www.notion.so/eqproduct/Fix-Textfield-clear-bug-067944c490364fe8aae2573403c11451
=> [G2M] TextArea - fixed logic when clearing textarea

.github/workflows/chromatic.yml, .github/workflows/main.yml, .github/workflows/npm-alpha.yml, .github/workflows/npm.yml, .github/workflows/storybook-deploy.yml
https://www.notion.so/eqproduct/Lumen-Labs-update-workflows-github-publish-85834c8acfaf46909e6485ff3fe9bab1?pvs=4
**Changes:**
- configured github workflows for storybook github page deployment
- updated github workflows to use v3 github actions & node 14.x
=> [G2M] GitHub deploy

src/base-components/button-base.js, src/components/button.js, stories/button.stories.js, tailwind.config.js
https://www.notion.so/eqproduct/Lumen-Labs-Button-e4523d3a3923416f8449b09f2df2481a?pvs=4
**Changes:**
- adjust the place of `classes` styling for html elements to be able to override styling
- added `content` key to `_classes`
- created `CustomStyling` story
**[Story](https://60d0cd6c298707003972699d-pjjwedlidr.chromatic.com/?path=/story/buttons--custom-styling)**
=> [G2M] Button - add custom styling

src/components/chip.js, stories/chip.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Chip-8de4525d02fa444bb2e7a7277d2199fa?pvs=4
**Changes:**
- configure `classes` prop to allow for custom styling
- add `Custom Styling` story
**[Story](https://60d0cd6c298707003972699d-viahvgkzyp.chromatic.com/?path=/story/chip--custom-styling)**
=> [G2M] Chip - add custom styling

src/base-components/modal-base.js, src/components/modal/content.js, src/components/modal/footer.js, src/components/modal/header.js, src/components/modal/index.js, stories/modal.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Modal-83cfc51fbf484d03bb761b90c5d251be?pvs=4
**Changes:**
- adjust the placing of `classes` styling in the tailwindcss styling string to be able to override styling
- created `CustomStyling` [story](https://60d0cd6c298707003972699d-mlijorbfas.chromatic.com/?path=/story/modal--custom-styling)
=> [G2M] Modal - add custom styling

src/base-components/card-base.js, src/components/card.js, stories/card.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Card-Offer-Offer-Special-Card-82080f8d378a4d3bb3b50ad53c4a1d11
**Card**
- adjust the placing of classes styling in the tailwindcss styling string to be able to override styling
- created CustomStyling [story](https://60d0cd6c298707003972699d-hteqvayfdt.chromatic.com/?path=/story/cards--custom-styling)
=> [G2M] Card - add custom styling

src/components/pagination.js, stories/pagination.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Pagination-869dccdf8249422693fd30b521e7a1db
**Pagination**
- created CustomStyling [story](https://60d0cd6c298707003972699d-kpnxbrqgbp.chromatic.com/?path=/story/pagination--custom-styling)
- set empty string as default value for classes
=> [G2M] Pagination - add custom styling

src/base-components/toast-base.js, src/components/navbar/index.js, src/components/navbar/navbar-header.js, src/components/navbar/navbar-item.js, src/components/progress-bar.js, src/components/toast.js, stories/toast.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Toast-d03e034bdd254137b3fbc5cb4216ab21?pvs=4
**Changes**
- configure classes to allow custom styling
- added identifying classname to each component
- added custom style story
=> [G2M] Toast - Custom Style

src/components/text-field.js, stories/textfield.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Textfield-Search-4b81e817dce04394b7bc43f6be36c4b4
**Search**
- created CustomStyling [story](https://60d0cd6c298707003972699d-pjqyjgcani.chromatic.com/?path=/story/textfield--custom-styling)
- add classname for borderlessClasses and set empty string as default value for container, root & input classes
=> [G2M] Search - add custom styling

src/modules/footer.js, stories/modules/footer.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Footer-2e4ec4ecc10c44b0833b77986ae46de3?pvs=4
**Changes**
- configure classes to allow custom styling
- added identifying classname to each component
- added custom style story
[Story](https://60d0cd6c298707003972699d-zzfzfqzwdc.chromatic.com/?path=/story/modules-footer--custom-style)
=> [G2M] Footer - Custom Style

src/components/carousel/carousel-item.js, src/components/carousel/index.js, src/hooks/carousel.js, src/index.js, src/modules/featured-content.js, stories/carousel.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Carousel-3b32e822f8354bc3865938fd24b6b6c0?pvs=4
- based on [figma file](https://www.figma.com/file/DfwOCrE6GJPFHPE96VFr8n/Web-App?node-id=954-28848&t=HDOrYwsMq5YXVHEr-0) for new paymi web app
- Added carousel component & carousel-item
- Added useCarousel hook to handle single & multi variant
[storybook](https://60d0cd6c298707003972699d-bqsnsaxhzz.chromatic.com/?path=/story/carousel--normal)
**Inspect element on browser for mobile & tablet view to test swipe feature**
=> [G2M] Carousel prototype with initial structure & design

src/base-components/switch-base/index.js, src/components/switch-rect/index.js, src/components/switch-round/index.js, src/components/switch-square/index.js, stories/switch.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Switch-7aa8710f1b024633924d954767f05cb5?pvs=4
**Changes:**
- configure `classes` prop to allow for custom styling
- add `Custom Styling` story
**[Story](https://60d0cd6c298707003972699d-ohkiivcsot.chromatic.com/?path=/story/switch--custom-styling)**
=> [G2M] Switch - allow custom styling

package.json, src/components/radio-group.js, src/components/radio.js, stories/radio.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Radio-0dc11e087fc0400c8d015392d5e3324e?pvs=4
**Changes:**
- adjust code for Custom Styling
- add `Custom Styling` story
**[Story](https://60d0cd6c298707003972699d-ogydtkibhr.chromatic.com/?path=/story/radio--custom-styling)**
=> [G2M] Radio - allow custom styling

src/base-components/accordion-base/index.js, src/base-components/accordion-base/panel-base.js, src/components/accordion/detailed-panel.js, src/components/accordion/index.js, src/components/accordion/panel.js, stories/accordion.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-Accordion-47716cf71fd84093a4b96adaa38c5952?pvs=4
**Changes**
- configure classes to allow custom styling
- added identifying classname to each component
- added custom style story
- added new component (DetailedPanel) to be used for complex accordions
[Story](https://60d0cd6c298707003972699d-hkzvtwhxpz.chromatic.com/?path=/story/accordion--detailed-panel)
=> [G2M] Accordion - Custom Style

package.json, src/base-components/input-base.js, src/components/text-field.js, stories/textfield.stories.js
https://www.notion.so/eqproduct/Lumen-Labs-TextField-b6bf5a2e06f34d8ca69e09f78fbba5f1?pvs=4
**Changes**
- Added param to keep endIcon on screen if value doesn't equal null
- Replaced React defaultProps with default params
=> [G2M] Textfield - HideIcon + Default Params

package.json, src/components/pagination.js, src/icons/chevron-left.js, src/icons/chevron-right.js
https://www.notion.so/eqproduct/Lumen-Labs-Pagination-enable-custom-arrow-af3bd0756e244601a1a3cd264b040534?pvs=4
- Added arrowLeft & arrowRight prop for pagination
- Added size prop for chevronLeft & chevronRight
=> [G2M] Pagination arrow custom

src/components/carousel/index.js, src/hooks/carousel.js
https://www.notion.so/eqproduct/Lumen-Labs-Carousel-add-pagination-feature-d04e6fbc2a2e4e0992f94ac635c27ddd?pvs=4
-Added pagination for carousel
=> [G2M] Carousel pagination feature

package.json, src/components/carousel/index.js
https://www.notion.so/eqproduct/Lumen-Labs-Carousel-pagination-next-bug-fix-026e69473484401f9b58d8ea8db36820?pvs=4
- Fixed carousel pagination next bug
=> [G2M] carousel - fix pagination next bug

package.json, src/components/tabs/index.js, src/components/tabs/panel.js, src/index.js, stories/tabs.stories.js
https://www.notion.so/eqproduct/Lumen-labs-Add-Tab-component-for-Setting-page-non-navigation-9aeccf9f6d7c4eb8a45f85c8a4c65d8a?pvs=4
**Changes**
- Added basic tab component
- Added option to provide custom styles
=> [G2M] Tabs - Added unstyled Tabs Component

package.json, src/components/date-picker.js
https://www.notion.so/eqproduct/Lumen-labs-Date-Picker-Style-438290b24e0b495ea075ff2f52e23588?pvs=4
**Changes**
- Added identifiers for the various states of a day on calendar (current day, hover day and selected day)
- Added option to change icon on input
=> [G2M] DatePicker - Style options

package.json, src/components/date-picker.js
**Changes**
- Fixed issue where user is unable to resize start icon for date-picker
- Removed ResetFocus function as it continued to cause issues in NextJS
=> [G2M] Date picker - Start Icon Size bug + ResetFocus Bug

package.json, src/components/carousel/index.js, src/hooks/carousel.js
https://www.notion.so/eqproduct/Lumen-labs-add-setpage-for-carousel-247f474886d1415eb80b0c9184543c04?pvs=4
- Added setPage prop for carousel
this is needed for the welcome-info page in onboarding
=> [G2M] carousel - add setpage prop

package.json, src/components/carousel/index.js, src/hooks/carousel.js
- Removed touchAction from carousel styling
=> [G2M] carousel - remove touchAction styling to allow Y axis scroll move

package.json, src/components/carousel/index.js, stories/carousel.stories.js
- Added currentIndex access for callback props
=> [G2M] Carousel enable callback

.github/workflows/chromatic.yml, .github/workflows/main.yml, .github/workflows/npm-alpha.yml, .github/workflows/npm.yml, .github/workflows/storybook-deploy.yml, package.json, src/components/date-picker.js, stories/date-picker.stories.js
https://www.notion.so/eqproduct/Lumen-Fix-date-picker-year-range-bug-acfd5511fc474f5dac25d730d91943da
- Add the fixedRange parameter to the date picker to allow setting a fixed year range.
- **Before:** 
- The year range dynamically shifts based on the selected year, causing earlier or later years to become unavailable.
- The years before minDate and the years after maxDate are still selectable in the year dropdown
- User able to select the end year that is earlier than the start year 
https://github.com/EQWorks/lumen-labs/assets/76548841/436da803-0291-4a37-b6ff-be03c3e096d5
- **After:**
- By setting fixedRange=true, the datepicker will stay in a fixed year range.
- The years before minDate and the years after maxDate will not shown in the year dropdown
- The year that is earlier than the …
=> [G2M] date-picker - allow user to set fixed year range

package.json, src/components/carousel/carousel-item.js, src/components/carousel/index.js, src/hooks/carousel.js, src/modules/footer.js, stories/carousel.stories.js
- Added progressbar for carousel
=> [G2M] carousel - add progressbar feature

package.json, src/components/dropdown-multi-search.js, stories/dropdown.stories.js
**Changed**
- Added `clearSearch` prop to multiselect search
- By default search is cleared when a value is selected
=> [G2M] MultiSelect - Search Value
